api:
  image: swapi:latest
  container_name: swapi
  ports:
    - "8080:8080"
graphql:
  image: swapi-graphql:latest
  container_name: graphql
  ports:
    - "3000:3000"
  links:
    - api:swapi
  environment:
    - NODE_PORT=3000
    - NODE_ENV=production
    - TRACER_ENABLED=true
    - API_CACHE=false
    - API_HOST=http://swapi:8080
